### ISSUE TITLE
Variety chest generate where vanilla chests should

### ISSUE THREAD

**Issue by Erinbutt** [SanAndreasP/VarietyChests#10]
Variety chests occasionally generate in with certain mods where there should be simple vanilla chests. This behavior has occured with mods such as Fossils and Archeology: Revival and Ocean Craft. Occasionally, the variety chests generate in vanilla dungeons as well. Is this a bug or a feature? I am currently using the 1.7.10-1.4.0 version. Will post screenshot if necessary
Thanks, 
Erin :D

**Comment by SanAndreaP** [comment]
Intended. You can disable this behavior in the config if you want.
