### ISSUE TITLE
Recipes unaffected by MineTweaker

### ISSUE THREAD

**Issue by ZeroLevels** [SanAndreasP/VarietyChests#8]
In the previous issue that I commented on, this mod (or possibly your manager pack) messed with recipes in general.  Unexpected outputs, not registering new ones from minetweaker, etc.

I imagine you have some sort of special handling for recipes or something, as recipes for your mod cannot be removed (and thus, altered), even though it can all be handled in the vanilla crafting table.  This is problematic for modern modpacks, as a lot of them are highly customized to the creator's taste these days.

I really hope this can be fixed, as I've been looking for a mod exactly like this. :)

**Comment by SanAndreasP** [comment]
I use my custom IRecipe implementation for some of my recipes (all of the VC recipes for that matter) to prevent registering the "same" recipe multiple times. I dunno how or even if MineTweaker allows alteration / messing around with IRecipes from mods, I highly doubt it however.
I may rethink the approach I use to enable compatibility, though. I have to see.

**Comment by SanAndreasP** [comment]
So I tested stuff out now and I fixed the crafting issue #7, but I tried removing a recipe from VC via MineTweaker and it errors, which is, I assume, an issue in MT itself.
I reported it here:
stanhebben/MineTweaker3#184

**Comment by ZeroLevels** [comment]
I tested this again.  I can't seem to wrap my head around what's changed, but the recipes are affected by MineTweaker now.  Both on MineTweaker 3.0.9C and 3.0.10.  I would guess you changed something on your end.  Though, it would seem that you can't select specific types...  It will remove all variants of the recipe if you try to remove them with the **.withTag** method.  It will have no affect at all if you use the **.onlyWithTag** method.  While this could be an inconvenience for some, it suits me just fine.

For best results with MineTweaker, it's best to turn off your NEI fix in the config, as even if the recipes are changed/removed, it still shows them in NEI.
